apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-multus
spec:
  config: '{ "cniVersion": "0.3.0", "name": "macvlan-multus", "type": "macvlan", "mode": "bridge", "master": "ens224", "ipam": { "type": "static"} }'
