apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ueransim-gnb 
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
    spec:    
      containers:
      - name: ueransim-gnb
        imagePullPolicy: {{ .Values.ueransim.image.pullPolicy }}
        image: "{{ .Values.ueransim.image.repository }}:{{ .Values.ueransim.image.tag }}"      
        env:
        - name: AMF_WORKER_NODEIP
          value: "172.33.23.124"
        - name: AMF_WORKER_NODEPORT
          value: "30412"       
