apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ueransim-gnb 
  labels:
    epc-mode: ueransim-gnb
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: ueransim-gnb
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        epc-mode: ueransim-gnb
    spec:    
      containers:
      - name: ueransim-gnb
        imagePullPolicy: IfNotPresent
        image: "docker.io/efatnar/ueransim:v1.1" 
        securityContext:
          privileged: true
        command: ["/bin/sh","-c"]
        args: ["./nr-gnb -c /open5gs/config-map/ueransim-gnb-configmap.yaml"]
        volumeMounts:
          - name: ueransim-gnb-config
            mountPath: /open5gs/config-map/ueransim-gnb-configmap.yaml
            subPath: "ueransim-gnb-configmap.yaml"
      volumes:
        - name: ueransim-gnb-config
          configMap:
            name: ueransim-gnb-config        
