# Default values for open5gs-epc-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ueransim:
  image:
    repository: docker.io/efatnar/open5gcore
    pullPolicy: IfNotPresent
    tag: "latest"

dnn: internet  

amf:
  mcc: 208
  mnc: 93
  tac: 7

# Primary/Native kubernetes interface
k8s:
 interface: eth0
