apiVersion: v1
kind: LimitRange
metadata:
  name: container-mem-limit-range
spec:
  limits:
  - default:
      memory: 1024Mi
      cpu: "500m"
    defaultRequest:
      memory: 512Mi
      cpu: "250m"
    type: Container
