# Default values for 5gcore-helm.

open5gs:
  image:
    repository: docker.io/efatnar/open5gcore
    pullPolicy: IfNotPresent
    tag: "v1.1"

webui:
  image:
    repository: docker.io/efatnar/open5gcore-webui
    pullPolicy: IfNotPresent
    tag: "v1.1"
  ingress:
    enabled: false
    hosts:
      - name: open5gs-epc.local
        paths: ["/"]
        tls: false

dnn: internet  

amf:
  mcc: 208
  mnc: 93
  tac: 7

k8s:
 interface: eth0
